general.live_config_reload = true

[window]
# decorations = "None"
option_as_alt = "OnlyLeft"
# startup_mode = "Maximized"

# https://formulae.brew.sh/cask/font-ubuntu-sans-nerd-font
[font]
size = 11
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }

# [cursor]
# style = { blinking = "On" }
