general.live_config_reload = true

[window]
# decorations = "None"
option_as_alt = "OnlyLeft"
# startup_mode = "Maximized"

# [font]
# size = 15
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# [cursor]
# style = { blinking = "On" }
