require("config.lazy")
require("config.tree")
require("config.telescope")
require("config.git")
require("config.lsp")

require("custom.autoformat")
require("custom.custom_script")
require("custom.custom_keymap")
require("custom.default")
