require("config.lazy")
require("config.tree")
require("config.telescope")
require("config.git")
require("config.lsp")

require("custom.autoformat")
require("custom.custom_script")
require("custom.custom_keymap")
require("custom.default")
require("custom.tmux_command_sender_from_nvim")
require("custom.live_grep")
require("custom.upscope")
require("custom.tmux_md")
